### PR TITLE
Issue 227 - error when replacing a file with a folder with the same name

### PR DESCRIPTION
**Pull request by arniotis**
Fix for #227

Noticed that you had already done something and noop'd it... anyway, it re-enabled it, and moved add bottom precedence. Together with the change in change.go, it seems to work - I'm running tests on a loop and zero failures so far

### CODE REVIEW

**Comment by odeke-em** [comment]
Nice! Thank you @arniotis for the good work. Could you make sure to `go fmt src/*` it and then squash the commits into one, and we are good to merge!

**Comment by arniotis** [comment]
Done, cheers

**Comment by odeke-em** [comment]
Thanks. LGTM. Please squash your commits into one.

**Comment by odeke-em** [comment]
Merged in with https://github.com/odeke-em/drive/commit/54ea24990f87f9fd94885a1edb3d1452c9f6d989.
Thank you very much for the contributions :)

**Pull request closed without merging**
