### PR TITLE
diff: prettify output

### PR DESCRIPTION
**Pull request by odeke-em**
Work in progress to address issue #89.

### CODE REVIEW

**Comment by odeke-em** [comment]
cc @ikwyl6 @l3iggs

**Comment by l3iggs** [comment]
@odeke-em you mentioned that this calls a locally installed diff utility, right? What happens if that's not installed?

**Comment by odeke-em** [comment]
No, it invokes `diff` as you would in your shell. If it doesn't exist diff doesn't run.

**Comment by odeke-em** [comment]
This was what I had mentioned from my previous comments
`
@l3iggs btw just to let you know drive does not perform its own diff. It just exec-s a subprocess to diff on your system with stdout and stderr connected. I had experimented around with different diff-ing go libraries and they did not work seem to work, consumed too much memory, produced bad output. I just gave up since it seemed like a time sink with no progress: possibly until I could find a good go diff library.
`

**Comment by odeke-em** [comment]
Oh sorry I read your question in a rush, if it isn't installed it throws an error informing one that the lookup for `diff` failed.

**Comment by l3iggs** [comment]
cool, I'd say merge it (although I don't have time to test)

**Comment by odeke-em** [comment]
Thank you. I'll wait for a few more hours for @ikwyl6. If they haven't responded by then, I'll merge it in because I am planning on making a release pretty soon.

**Comment by ikwyl6** [comment]
I can't test for atleast another 6-8 hours. So maybe just put it in.

**Comment by odeke-em** [comment]
Thanks for the response @ikwyl6. No worries, I get back home in about 10 hours anyways so I'll wait for you to test it out.

**Comment by ikwyl6** [comment]
So if I want to apply this change/commit to test it to my local code (https://github.com/odeke-em/drive/commit/0e5b686eea21f21ddd51db1c178539fb7362267d?diff=unified) how can I do it? Follow the "Applying Patches" on your front page and change "patch-1" to "6afbeff"? Or use git cherry-pick somehow?

Not that familiar with git. Sorry.

**Comment by odeke-em** [comment]
@ikwyl6, replace 'patch-1' with 'diff-prettify'.

**Comment by odeke-em** [comment]
You can check this out by a normal install since it is now in master.

**Pull request merged**
