### PR TITLE
Readme: Correct ignore-name-clashes arg

### PR DESCRIPTION
**Pull request by cacack**
Minor change to correct name of `-ignore-name-clashes` argument.

### CODE REVIEW

**Comment by odeke-em** [comment]
Hello @cacack, thank you for this PR and welcome to drive!
So, in regards to the PR, currently the command line args parser uses `-` and `--` interchangeably, so the original is still valid.

**Comment by cacack** [comment]
Ahh. Didn't realize that.  I had also added 'es' to the end of the arg which was what actually fixed the problem.

**Comment by cacack** [comment]
I've adjusted the commit to reflect just the need to add the 'es' to the argument.

**Comment by odeke-em** [comment]
Awesome! Good catch and thank you for fixing this. LGTM!

**Comment by odeke-em** [comment]
So just one last thing before I merge this in. Would you mind opening an issue describing the problem. This is for purposes of me not forgetting to give you credit in the next release and for easy lookups later on :)

**Comment by cacack** [comment]
Certainly!

**Comment by cacack** [comment]
Issue #382 opened.

**Comment by odeke-em** [comment]
Awesome! Merging this in. Thank you for carefully examining it :)

**Pull request merged**
