### PR TITLE
godep introduced

### PR DESCRIPTION
**Pull request by odeke-em**
This PR is a work in progress meant to address issue https://github.com/odeke-em/drive/issues/206. It bundles dependencies into drive-gen/Godeps.

+ Firstly to check out the branch

```shell
$ go get -u github.com/odeke-em/drive/drive-gen && cd $GOPATH/src/github.com/odeke-em/drive/drive-gen
$ git fetch --all && git checkout go-deps
```

+ Using godep
```
$ cd $GOPATH/src/github.com/odeke-em/drive/drive-gen && godep save
```

+ Unravelling/Restoring dependencies
```
$ cd $GOPATH/src/github.com/odeke-em/drive/drive-gen && godep restore
```

Please see file `drive-gen/README.md` for more information.

### CODE REVIEW

**Comment by n4cer** [comment]
@odeke-em thanks for working on it!
 i'm on holidays and will look at it in monday

**Comment by n4cer** [comment]
I don't know what it is but when executing "godep save" it tells me:
```
godep: directory "/usr/lib/go/src" is not using a known version control system
godep: error loading dependencies
```
Is there something wrong with my setup?

**Comment by odeke-em** [comment]
To be honest, I've never used godep so this is all just pure speculation derived from the error reported :)

However,
Probably your Go binary was not built from source, it probably got installed by a download from the website or package. Would you mind trying installing from source but please make sure your GOPATH is well setup, that you can see how to do here https://github.com/odeke-em/drive#requirements. Then install go from source

**Comment by n4cer** [comment]
godep is now working, but rev b1cb1e5a90decb4e0de7fd93b16bf6bc6cc6ecf1 doesn't exsits in the "github.com/odeke-em/google-api-go-client" repository.

**Comment by odeke-em** [comment]
Oops, sorry I hadn't pushed up changes from github.com/odeke-em/google-api-go-client. Please try again.

**Comment by n4cer** [comment]
works fine now

**Comment by odeke-em** [comment]
Thanks @n4cer for testing it. Now an important question here is how do we package the dependencies in drive for users who don't need them? -- this is because majority of the users have been building drive until now without having to use godeps, plus packages in the project increase the size of the project. Please let me know your thoughts :) Also while we are at it, let me summon @shaggytwodope  @dgvirtual @IS-smcleod plus any other Linux folks to pitch in ideas.
To be honest it is only 772K in drive-gen/ vs 172K in src/ and given that we are still in the KB range this is okay, but just exploring other options
screen shot 2015-06-04 at 8 45 43 pm

**Comment by odeke-em** [comment]
Merging this in since it fits the use case. Thank you for reporting the need for this. I'll try my best to always run Godeps before version release.

**Pull request merged**
