### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by sselph**
Was broken by adding a make file.

### CODE REVIEW

**Comment by odeke-em** [comment]
Thank you thank you @sselph. LGTM!

**Comment by odeke-em** [comment]
Btw, could you change the commit message to `Fix .travis install step` instead?

**Comment by sselph** [comment]
Done

**Comment by odeke-em** [comment]
Solid. Merging it in. Thanks again and happy 666th PR 😂

**Comment by sselph** [comment]
Yeah when I saw that I was disappointed the PR wasn't more interesting.

**Comment by odeke-em** [comment]
Hehe here is a distraction https://www.youtube.com/watch?v=v6cnQA17xIw

**Pull request merged**
