### PR TITLE
Fixes #978

### PR DESCRIPTION
**Pull request by idvoretskyi**
README: Fix grammar in Google Service Accounts section and add GSA link

Replaces #978 which was created by @ukd1

cc @odeke-em

### CODE REVIEW

**Comment by odeke-em** [comment]
Great, thank you @idvoretskyi for taking on the patch. Just for the purpose of posterity and for a proper commit message, please make your commit message

```
README: Fix grammar in Google Service Accounts section and add GSA link

Replaces #978 which was created by @ukd1
```

**Comment by ukd1** [comment]
@odeke-em btw - sorry about going AFK; I didn't see the notification in the sea of them I get!

**Comment by idvoretskyi** [comment]
@odeke-em updated :)

**Comment by odeke-em** [comment]
Sorry for the late reply @idvoretskyi I've been very busy unfortunately. What I meant in  https://github.com/odeke-em/drive/pull/997#issuecomment-372560651 was to replace the actual git commit message so
```shell
git commit --amend
```
and then
```shell
README: Fix grammar in Google Service Accounts section and add GSA link

Replaces #978 which was created by @ukd1
```
The reason is to keep a reference and give credit to @ukd1. 
This time I'll respond promptly after you've made the update :)

**Comment by idvoretskyi** [comment]
@odeke-em just noticed this in my backlog - fixed :)

**Pull request merged**
