### PR TITLE
linux: desktopEntry for docs.google.com affiliates

### PR DESCRIPTION
**Pull request by odeke-em**
This PR is meant to address #74. Feedback, testing and a go-ahead from Linux users is welcome.
Summoning the Linux users!

### CODE REVIEW

**Comment by dgvirtual** [comment]
So I updated drive with this patch as suggested in thread #74.

I have a google document called "test".

    $ drive pull --force test
    Resolving...
    Everything is up-to-date.

    $ ls test*
    test

No change... Lets try with --force option:

    $ drive pull --force test
    Resolving...
    M /test
    Modification count 1
    Yroceed with the changes? [Y/n]:  / 
    1 / 1 [=========================] 100.00 % 0

Let's see what changed.

$ ls -lh test*
-rw-rw-r-- 1 dg dg    0 Vas 27 17:06 test
-rw-rw-r-- 1 dg dg  194 Kov 17 17:29 test.desktop

I expected the same dummy file "test" to be changed, but I see a new file with *.desktop extension instead. I think it would be better to have the empty file fill with the contents of the *.desktop file – it would still be recognized correctly by the file managers (most of them at least).

When I click the file in Dolphin file manager, it opens the document online. Great! Let us see what is inside:

    $ cat test.desktop 
    [Desktop Entry]
    Icon=application/vnd.google-apps.document
    Name=test-
    Type=Link
    URL=https://docs.google.com/a/lapas.info/document/d/1nR2ZzEe6XqjEUVqeQdRkI3OqzR2lI5PQhzlBgixkbS8/edit?usp=drivesdk

I see a dash after the Name parameter value, that should not be there (although it is not a problem). 

I also see you have chosen to include other than the generic icon, – the default mime type for google documents (I see spreadsheets get their own default mime type) - great! We just need to figure out how to easily get those mime types and corresponding icons into the distributions (for I see that my distribution, Kubuntu 14.04, does not have these mime types). 

Now, the interesting thing: 

    $ drive push test*
    Resolving...
    + /test.desktop
    Addition count 1 src: 194.00B
    Proceed with the changes? [Y/n]: Y
    1 / 1 [=================] 100.00 % 1s

I would expect those files to be non-pushable...

So, my suggestions: 

1. Remove the dash at the end of the Name key value
2. Include the contents of desktop file into the currently empty files representing the google docs/sheets etc. - I do not think we need separate *.desktop files
3. In case the separate *.desktop files were to stay, make them non-pushable. 
4. We have to figure out a way to add mime types and google apps icons to our distributions.

**Comment by odeke-em** [comment]
I'll jump onto this in 10 hours when I get back home.

**Comment by odeke-em** [comment]
@dgvirtual concerns 1-3 addressed in latest commit, please retry the build. As for 4, that'll require some involvement and ideas from you and other Linux users on how to distribute the icons. Otherwise every file comes with its ThumbnailUrl for which a download can be made.

**Comment by dgvirtual** [comment]
OK, the empy file filled with *.desktop file content, no separate *.desktop file - great! 

I still see 
    Icon=application/vnd.google-apps.document
while it should be 
    Icon=application-vnd.google-apps.document

Regarding the icons; what is the status of drive as regards the copyright holder? Maybe Google can license the icons for use in drive? If you do not work for Google, maybe you could ask Rakyl? I have little idea on how it should go. If we cannot hope to get the original icons from google, we either have to specify different icons that already exist in most Linux distributions.

**Comment by odeke-em** [comment]
As for the mimeType, that is the original mimeType as it is sent over the wire.
As for getting icons from Google https://github.com/google/material-design-icons contains a repo of icons that Google open sourced. Please browse around and if a set cannot be found, then I'll try contacting the Google Drive team or Google Open Source programs office or even the licensing office to ask if we could get the icons that they use for Google Drive on other platforms. Please let me know what you find.

**Comment by dgvirtual** [comment]
Hi, 

> As for the mimeType, that is the original mimeType as it is sent over the wire. 

do you mean that "application/vnd.google-apps.document" is something that is set by google, not by you? Anyway, it has to be modified when used as icon reference in a *.desktop file, so it should perhaps be changed to "vnd.google-apps.document" or "application-vnd.google-apps.document". Otherwise it will not refer to any icon.

As for the source of Google open source icon set - I have reviewed the index available here (http://google.github.io/material-design-icons/) and the google documents icons are missing.

**Comment by odeke-em** [comment]
```shell
do you mean that "application/vnd.google-apps.document" is something that is set by google, not by you? Anyway, it has to be modified when used as icon reference in a *.desktop file, so it should perhaps be changed to "vnd.google-apps.document" or "application-vnd.google-apps.document". Otherwise it will not refer to any icon.
```
Yes not modified by myself, but directly from Google. Are you sure? If so, please find out the standard formatting to cover as many cases in case any reformatting of the string is needed.

Alright, let me contact someone about the icons. However, I feel like that is a deeper issue of its own and will involve more packaging of the icons. I'd rather first finish off and implement the basic functionality then worry later the icon images.

**Comment by odeke-em** [comment]
Oh snap, I had not re-read your edit. Thank you for the clarification. I am taking a look at that now.

**Comment by odeke-em** [comment]
Unfortunately according to the response from https://twitter.com/odeke_et/status/578242967867031552,
we cannot use the icons suggested in open source projects.

**Pull request merged**
