### PR TITLE
mkdirAll ensure parent for arbitrary nestings exists

### PR DESCRIPTION
**Pull request by odeke-em**
Ensure that arbitrarily remote nested paths can be pushed to by recursively creating parents if non-existant.
This PR addresses issues #50 and #46. @bausmeier and @guruthree, works for me but would you kindly help me test out if you this solves your issue. In case you need to install the changes and test it out:

```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git fetch --all
$ git checkout fix/mkdirAll-feature
$ # If you think you have stale changes, please run
$ # git pull origin fix/mkdirAll-feature
$ go get github.com/odeke-em/drive/cmd/drive
```
should install it.

### CODE REVIEW

**Comment by timberswrx** [comment]
I was getting the same error. I've made the update following the directions above and have started a push. I'm no longer getting the errors, so things look good. I'm pushing a lot of data, about 42G, so it will be a while before it's done. I'll update then.

**Comment by guruthree** [comment]
Looks to fix the issue for me as well.

**Comment by odeke-em** [comment]
@bausmeier please let me know if this fixes it for you.

**Comment by bausmeier** [comment]
Sorry for the slow response. Works for me :+1:

**Comment by innerteapot** [comment]
Working a lot better for me too. Thanks :+1:  

I'm getting a few errors but it looks like a separate issue:

screen shot 2015-01-27 at 9 23 12 pm

**Comment by odeke-em** [comment]
@bausmeier no worries, glad to know it works. @innerteapot that's an interesting error, did you setup drive using your own project API credentials? What might have changed? The reason am asking this is because that error shows invalid credentials so if you entered used your own API keys please make sure OAUTH2.0 is enabled and so is access to Google Drive and its scopes. If this persists please open up a separate issue and we can examine it there.

**Comment by timberswrx** [comment]
It looked like it was working for me, but I cancelled the push after a day, figuring I could continue it later. I don't know if that was what caused the issue, but when I went to google drive, none of my files were there. Instead, I had thousands of "Untitled" files in the root of drive, all with zero length. It's been taking me forever to try and get rid of them and I'm not done yet. Anyone know a better way to get rid of all those "Untitled" files?

**Comment by odeke-em** [comment]
@timberswrx that is unfortunate. It was because of that Google API change that I mentioned as it caused the same issues for me too the whole of Sunday, but that I fixed by using a stable API. Too bad for that, I could help and provide a wild card-ish method for trashing files as well as listing but unfortunately am just leaving home in a few minutes, if you can wait for 9 hours, I could be of help.

**Comment by timberswrx** [comment]
I'll continue removing files from drive on the web and see how many I can get rid of that way. What do I need to do to make sure I'm using the correct version of drive?

**Comment by odeke-em** [comment]
For starters, the normal install with an update as specified by the README. I am now and will be keeping a lock on the API clients that drive uses to avoid such issues. My apologies that you got affected by Sunday's drama.

**Comment by timberswrx** [comment]
I'm not sure how to get this to build again. I did the updates as listed above to get the fix and now the build as specified in the README is failing. How do I reset?

**Comment by odeke-em** [comment]
Firstly make sure you are on master
```shell
$ cd $GOPATH/src/github.com/odeke-em/drive
$ git checkout master
```
Next will be to perform the update
```shell
$ go get -u github.com/odeke-em/drive/cmd/drive

# To verify that you are using the curated Google Golang API
$ [ -d $GOPATH/src/github.com/odeke-em/google-api-go-client ] || echo 'You don't have the curated Google Golang API'
```

**Comment by odeke-em** [comment]
@timberswrx just in case for the future you have lots of files to trash, in https://github.com/odeke-em/drive/commit/0459854f97e50ec4eafc27f8c0aa92a884cd4e45 I have added the ability to perform case insensitive prefix matches ie if you wanted to trash all the files that begin with "Untitled" "Photos" or "aero" in path mnt/logs
```shell
$ cd ~/gdrive/mnt/logs
$ drive trash -matches Untitled Photos aero
```
Untrashing works the same way.
Don't forget to get the latest from master :)
Hope this can help! Please feel free to reach out in case of anything.

**Comment by timberswrx** [comment]
That sounds great. It would have been a big help. This is working great for me now. I'm uploading one sub-directory at a time so I have better visibility and it's going very well.

**Pull request merged**
