### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bjohas**

### CODE REVIEW

**Comment by odeke-em** [comment]
Thank you @bjohas for the PR, good plan documenting that.

Would you mind amending the commit message to
```shell
README: document -notify=false

Fixes https://github.com/odeke-em/drive/issues/791

Document that using -notify=false turns off notifying
and that by default -notify is set.
```

**Comment by bjohas** [comment]
Hi @odeke-em, 

Sorry, but it seems it's not easily possible/recommended: https://help.github.com/articles/changing-a-commit-message/. However, I've made another commit / PR, this time with comment. Hope that fixes it!

**Comment by odeke-em** [comment]
Awesome, thanks. Just one last thing and we can then merge it in
```shell
$ git rebase -i head~2
```

and then when it asks you to combine all the messages, set it as 
```shell
README: document -notify=false

Fixes #791

Document that using -notify=false turns off notifying
and that by default -notify is set.
```

No worries @bjohas, in the future, you can just do
```shell
$ git commit -a --amend
``` 

and that adds your file as well as amends the same commit.

**Comment by odeke-em** [comment]
Also after amending the commit, send it by a push with `--force` to overwrite and change the shasum.

**Comment by odeke-em** [comment]
Thank you @bjohas for the PR, I squashed the commits into one and merged it in https://github.com/odeke-em/drive/commit/71cbd2f5b03c8c922f146a097b294ffb61b9d132.

**Comment by bjohas** [comment]
Thanks!!

**Pull request closed without merging**
