### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by intrd**
Fix strange issues on Ubuntu and Mint installations

### CODE REVIEW

**Comment by intrd** [comment]
Good idea, a troubleshooting or known problems section would be interesting.. it took me hours to find this solution.. 
thanks! awesome work.

**Comment by chevillet** [comment]
Glad it helped even if it was hidden in issues history ;)
I also battled a lot with Go installation on old Ubuntu servers before finding gvm!

**Comment by shaggytwodope** [comment]
You do know a ppa is provided that can be used on mint/ubuntu setups? I mention this because more instructions a user is given... more that can go wrong. Regardless, if this is how people wanna install it needs some more notes.

The script requires an export when compiling 1.5 from 1.4. And needs a few notes for the depends: curl git mercurial make binutils bison gcc build-essential. 

At first glance this seems like a fairly bad idea however, users may not understand this is compiling go for them, any security or strange go issues will NOT be updated in the future unless they do so manually. Their package manager is no longer going to manage go... this is a bad idea to me to even encourage.

**Comment by idvoretskyi** [comment]
+1 to skip this.

There is a PPA, that solves the issues with .deb installation; also we really have wiki.

**Comment by chevillet** [comment]
I would not recommend to add this to the README either for the reasons you stated.
However, the PPA is not always the solution, it's not always up to date and it's useful for users who want to test the latest drive features to be able to install it from master. And, with the default go version, under Ubuntu 14.04 LTS (which is still supported), it's impossible to compile (pr at least it was when I posted this a few months ago).

**Comment by shaggytwodope** [comment]
@chevillet completely and totally correct. I think we/someone should add this to the wiki. And reference the directions from the readme. @odeke-em tends to release only when well tested. So as to only provide a stable release. But the info should be made accessible regardless.

That all said, if any feature or fix should ever need included in the ppa. Just let me know.

**Comment by chevillet** [comment]
@shaggytwodope It goes without saying but my message was not a critic of @odeke-em or your work! It's super cool to have a living project like drive and to see the PPA updated almost instantly after every release!

I added a Troubleshooting section to the wiki page: https://github.com/odeke-em/drive/wiki/Home/532cec38f5ed650826d8756cb6074a5c48c535e7

@intrd Feel free to reference it in the README :)

**Comment by odeke-em** [comment]
Hello there folks! Thank you @intrd for the PR, thanks @canpolat, @chevillet, @shaggytwodope, @idvoretskyi for the review and for the discussion.

Yes I agree with @canpolat, we should make a trouble shooting section. I personally have found,
that the instructions on how to install Go from the official source as linked in the README https://github.com/odeke-em/drive#requirements
 are just a 5 step process that gets you the latest, and as we've all found that on Ubuntu trying to using apt-get  installs the wrong version.

Thanks for the wiki entry @chevillet, and everyone.

As was discussed above, we don't think this belongs in the README, so I'll close this PR.
However, I'll mark it as 0.3.9 so that for that release, I'll detail that information. Hope that
helps future users too find it.

**Pull request closed without merging**
