### PR TITLE
Move + Rename

### PR DESCRIPTION
**Pull request by odeke-em**
Move + Rename implemented
Work in progress to address issues #85 and #86

### CODE REVIEW

**Comment by odeke-em** [comment]
@kcwu, if I may, could I ask for your help in testing this and get your views as well?

**Comment by kcwu** [comment]
Sure. I can test it maybe 10 hours later. Just few questions first:

 1. What does this mean?
```$ drive rename openSrc/2015 2015-Contributions```
Does openSrc/2015 become openSrc/2015-Contributions?
 2. And for both rename and move, what happens if there is already an existing item with the same name?
 3. Just to make sure. This two command is pure remote, right?

**Comment by odeke-em** [comment]
```
1. What does this mean? $ drive rename openSrc/2015 2015-Contributions Does openSrc/2015 become openSrc/2015-Contributions?
```
Yes

```
 2. And for both rename and move, what happens if there is already an existing item with the same name?
```
For rename: 
screen shot 2015-03-11 at 2 01 30 am

Move should allow directory nesting only if the destination directory exists. But you should not be able to nest a directory in itself.

```
3. Just to make sure. This two command is pure remote, right?
```
Yes in deed.

**Comment by odeke-em** [comment]
Thank you for the eyes and for the offer!

**Comment by kcwu** [comment]
1. ```drive rename dir1 dir2/dir3```
"dir2/dir3" is valid name for google drive, but probably not what users want. I don't know should we do anything or just accept it.

2. removeParent seems don't work for folders in root?
```
$ mkdir dir1 dir2
$ touch dir1/dir1.txt
$ drive push -no-prompt dir1 dir2
$ drive move dir1 dir2
$ drive list -r -m=-1 dir1 dir2
/dir1/dir1.txt
/dir2/dir1
/dir2/dir1/dir1.txt
```

**Comment by odeke-em** [comment]
Very good points:
```
1. drive rename dir1 dir2/dir3
"dir2/dir3" is valid name for google drive, but probably not what users want. I don't know should we do anything or just accept it.
```
What happens if a user types:
```shell
$ drive rename flux https://content.com
```
See what I mean?

```
2. removeParent seems don't work for folders in root?
```
In deed, I was trying to avoid ripping out root, but clearly I had prematurely considered a non existant case. I'll fix this in a second.

**Comment by kcwu** [comment]
```drive move dir1/dir2/dir3 dir1/dir2```
This will make dir3 parentless.

**Comment by odeke-em** [comment]
Looks like a reordering problem, trivial fix is to remove first then insert.

**Comment by odeke-em** [comment]
Thank you for that edge case, I like that. Anyways am going to be off for about 12 hours.

**Comment by kcwu** [comment]
However, as your original comment said, now it may become orphan due to remove first.

**Comment by odeke-em** [comment]
Please try it out and let me know, as I won't be able to make any compiles for a bit till I get back home.

**Comment by kcwu** [comment]
Using your last change,
```
drive move a a/b
```
`a` will become orphan

**Comment by odeke-em** [comment]
Good point, I'll focus on trying to get it right when I get home, instead of hacking. Please help me think of as many edge cases as you can think of :) I very much appreciate your help and input.

**Comment by kcwu** [comment]
two more interesting cases:

```drive move a/foo b/foo dest```
doesn't warn about -force

```drive move a/b a/b/c dest```
maybe need to give warning or error? i'm not sure

**Comment by ikwyl6** [comment]
Why not just follow how *nix systems do it? I don't think the above cases would work on command line linux. Why not just keep it simple, dir1 and dir2 and catch the few orphan cases.

**Comment by kcwu** [comment]
Yes, that's the problem. The current implementation return success for cases expected failed.

**Comment by odeke-em** [comment]
Am back home. 
@ikwyl6, I don't quite get what you mean by the cases would fail on Linux..
I implore you to try 
screen shot 2015-03-11 at 9 14 45 pm
screen shot 2015-03-11 at 9 27 15 pm

@kcwu 
```
drive move a/foo b/foo dest
doesn't warn about -force
```
I will let this be for now, as I'd rather get the basic functionality in.

```
drive move a/b a/b/c dest
maybe need to give warning or error? i'm not sure
```
Agreed. I'll just print out the error otherwise aborting might make for painful user experience in case folks have multiple paths to move.

**Comment by odeke-em** [comment]
Turns out I needed just some sleep, I got time and have pushed up a commit that should clear out the failing cases namely:
+ Looking up if a duplicate path is present on trying to move a file, if so follow the `--force` semantics and usage.
+ Nesting a parent into a child is detected.
I'll be merging this in otherwise. Thank you very much everyone.

**Pull request merged**
