### PR TITLE
Awesome one-line backup tar.gz on the fly

### PR DESCRIPTION
**Pull request by aerth**

### CODE REVIEW

**Comment by odeke-em** [comment]
Hey @aerth thanks for this PR and welcome to drive. Now this is pretty dope, I like it.
I'll just post one comment on it then we'll be good to merge.

**Comment by odeke-em** [comment]
Actually just one last thing, would you mind creating an issue requesting this so that when am drafting the next release I can get this in and give you the credit without forgetting? It also helps later on for navigating. Thanks

**Comment by odeke-em** [comment]
I'll merge it in as am making the release right now. Thank you very much for the PR! LGTM!

**Comment by aerth** [comment]
a typo made it in! here comes another PR

**Comment by odeke-em** [comment]
Ooh I already made the fix in master and made a release. Please see https://github.com/odeke-em/drive/releases/tag/v0.3.1

**Comment by aerth** [comment]
epic! great go program!

**Comment by odeke-em** [comment]
Thanks @aerth! Cheers.

**Pull request merged**
