### PR TITLE
Added SVG versions of the current icons.

### PR DESCRIPTION
**Pull request by IS-smcleod**

### CODE REVIEW

**Comment by odeke-em** [comment]
Hello again @IS-smcleod. This is cool, thank you!
Would you mind opening an issue to indicate that you want to add in the svg version of icons? This is because I use issues to track progress as well as for backtracking with history. I would like to give you credit for this work on the next release so an issue keep me upto task when am writing up the changes.

**Comment by IS-smcleod** [comment]
Sure, just opened issue #198.

**Comment by odeke-em** [comment]
LGTM! Merging this in. Thank you for working on this.

**Comment by dgvirtual** [comment]
Great!

**Pull request merged**
